"""
Tipos de operación para trazabilidad de la aplicación (AppTrace).
"""

OPERATION_LOGIN = 1
OPERATION_CREATE_ORDER = 2
OPERATION_EDIT_RESULT = 3
OPERATION_VALIDATE_RESULT = 4
OPERATION_INVALIDATE_RESULT = 5
OPERATION_CHANGE_STUDY_STATE = 6
OPERATION_EDIT_DEMOGRAPHICS = 7
OPERATION_SEND_RESULT_WHATSAPP = 8
OPERATION_SEND_RESULT_EMAIL = 9
OPERATION_UPLOAD_ANNEXED = 10
OPERATION_DELETE_ANNEXED = 11
OPERATION_MANAGE_SEROTECA = 12
OPERATION_MANAGE_GRADILLA = 13
OPERATION_MANAGE_REMISSION = 14

OPERATION_TYPES = {
    OPERATION_LOGIN: "Inicio de sesión",
    OPERATION_CREATE_ORDER: "Creación de Orden",
    OPERATION_EDIT_RESULT: "Edición de Resultado",
    OPERATION_VALIDATE_RESULT: "Validación de Resultado",
    OPERATION_INVALIDATE_RESULT: "Invalidación de Resultado",
    OPERATION_CHANGE_STUDY_STATE: "Cambio Estado de Estudio",
    OPERATION_EDIT_DEMOGRAPHICS: "Edicion Demograficos",
    OPERATION_SEND_RESULT_WHATSAPP: "Envío de Resultado por WhatsApp",
    OPERATION_SEND_RESULT_EMAIL: "Envío de Resultado por Correo Electrónico",
    OPERATION_UPLOAD_ANNEXED: "Carga de Anexo a Resultado",
    OPERATION_DELETE_ANNEXED: "Eliminación de Anexo a Resultado",
    OPERATION_MANAGE_SEROTECA: "Gestión de Seroteca",
    OPERATION_MANAGE_GRADILLA: "Gestión de Gradilla",
    OPERATION_MANAGE_REMISSION: "Gestión de Remisión",
}
